module CorbaCatApp {
  interface ICorbaCat {

    //Registra un jugador y regresa su id
    long registrarJugador(in string nombreJugador);

    //Circulo = 0 tacha  = 1. Este metodo regresa la id del juego
    long registraJuego(in long idJugador, in long circulo_tacha);

    //Regresa verdadero si fue exitosa la operacion
    boolean registrarCoordenadas(in long x, in long y, in long id_juego, in long tipo_jugador);

    long obtenerJugadaX();

    long obtenerJugadaY();

    boolean terminarJuego(in long id_juego);

  };
};